CREATE TABLE FACTOR (
    FACTOR_SID BIGINT IDENTITY(1,1) NOT NULL,
	PROPERTY_NAME VARCHAR(32) NOT NULL,
    DISPLAY_NAME VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(256),
	FACTOR_TYPE VARCHAR(32) NOT NULL,
    CONSTRAINT [PK_FACTOR] PRIMARY KEY CLUSTERED ([FACTOR_SID] ASC)
);