CREATE TABLE PATIENT (
    PATIENT_SID BIGINT IDENTITY(1,1) NOT NULL,
    MRN VARCHAR(32) NOT NULL,
    FACILITY_ID VARCHAR(32) NOT NULL,
    ENTERPRISE_NUM VARCHAR(32),
    FIRST_NAME VARCHAR(64),
    LAST_NAME VARCHAR(64),
    MIDDLE_NAME VARCHAR(64),
    BIRTH_DATE DATETIME2,
    GENDER VARCHAR(32),    
    CONSTRAINT [PK_PATIENT] PRIMARY KEY CLUSTERED ([PATIENT_SID] ASC)
);