CREATE TABLE VITALS_RULE (
    VITALS_RULE_SID BIGINT IDENTITY(1,1) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
    DESCRIPTION VARCHAR(256),
	RISK_LEVEL VARCHAR(32) NOT NULL,
	DEFINITION VARCHAR(max) NOT NULL,
    CONSTRAINT [PK_VITALS_RULE] PRIMARY KEY CLUSTERED ([VITALS_RULE_SID] ASC)
);