CREATE TABLE PATIENT_FACTOR (
    PATIENT_FACTOR_SID BIGINT IDENTITY(1,1) NOT NULL,
    PATIENT_SID [bigint]  NOT NULL,
    FACTOR_SID [bigint]  NOT NULL,
    RECORD_VALUE VARCHAR(64) NOT NULL,
	RECORD_ENTRY_DATE DATETIME2 NOT NULL,
    CREATED_BY VARCHAR(256) NOT NULL,
    CREATED_DATE DATETIME2 NOT NULL CONSTRAINT DF_PATIENT_FACTOR_CD DEFAULT SYSDATETIME(),
    MODIFIED_BY VARCHAR(256) NOT NULL,
    MODIFIED_DATE DATETIME2 NOT NULL CONSTRAINT DF_PATIENT_FACTOR_MD DEFAULT SYSDATETIME()
    
    CONSTRAINT [PK_PATIENT_FACTOR] PRIMARY KEY CLUSTERED ([PATIENT_FACTOR_SID] ASC)
);